mv afghanistan ../known-percent-afghanistan
mv aland-islands ../known-percent-aland-islands
mv albania ../known-percent-albania
mv algeria ../known-percent-algeria
mv allemagne ../known-percent-allemagne
mv argentina ../known-percent-argentina
mv australia ../known-percent-australia
mv austria ../known-percent-austria
mv autriche ../known-percent-autriche
mv belarus ../known-percent-belarus
mv belgique ../known-percent-belgique
mv belgium ../known-percent-belgium
mv bolivia ../known-percent-bolivia
mv bosnia-and-herzegovina ../known-percent-bosnia-and-herzegovina
mv brazil ../known-percent-brazil
mv bulgaria ../known-percent-bulgaria
mv cambodia ../known-percent-cambodia
mv canada ../known-percent-canada
mv chile ../known-percent-chile
mv china ../known-percent-china
mv cote-d-ivoire ../known-percent-cote-d-ivoire
mv croatia ../known-percent-croatia
mv cyprus ../known-percent-cyprus
mv czech-republic ../known-percent-czech-republic
mv denmark ../known-percent-denmark
mv deutschland ../known-percent-deutschland
mv ecuador ../known-percent-ecuador
mv egypt ../known-percent-egypt
mv en ../known-percent-en
mv estonia ../known-percent-estonia
mv etats-unis ../known-percent-etats-unis
mv europa ../known-percent-europa
mv europe ../known-percent-europe
mv european-union ../known-percent-european-union
mv faroe-islands ../known-percent-faroe-islands
mv finland ../known-percent-finland
mv france ../known-percent-france
mv france-spain ../known-percent-france-spain
mv francia ../known-percent-francia
mv frankreich ../known-percent-frankreich
mv french-guiana ../known-percent-french-guiana
mv french-polynesia ../known-percent-french-polynesia
mv georgia ../known-percent-georgia
mv germany ../known-percent-germany
mv greece ../known-percent-greece
mv guadeloupe ../known-percent-guadeloupe
mv guernsey ../known-percent-guernsey
mv guinea ../known-percent-guinea
mv hong-kong ../known-percent-hong-kong
mv hungary ../known-percent-hungary
mv iceland ../known-percent-iceland
mv india ../known-percent-india
mv indonesia ../known-percent-indonesia
mv iraq ../known-percent-iraq
mv ireland ../known-percent-ireland
mv israel ../known-percent-israel
mv italy ../known-percent-italy
mv japan ../known-percent-japan
mv jordan ../known-percent-jordan
mv kenya ../known-percent-kenya
mv kuwait ../known-percent-kuwait
mv latvia ../known-percent-latvia
mv libya ../known-percent-libya
mv lithuania ../known-percent-lithuania
mv luxembourg ../known-percent-luxembourg
mv malaysia ../known-percent-malaysia
mv mali ../known-percent-mali
mv malta ../known-percent-malta
mv martinique ../known-percent-martinique
mv mauritius ../known-percent-mauritius
mv mexico ../known-percent-mexico
mv moldova ../known-percent-moldova
mv montenegro ../known-percent-montenegro
mv morocco ../known-percent-morocco
mv myanmar ../known-percent-myanmar
mv netherlands ../known-percent-netherlands
mv new-caledonia ../known-percent-new-caledonia
mv new-zealand ../known-percent-new-zealand
mv north-macedonia ../known-percent-north-macedonia
mv norway ../known-percent-norway
mv oman ../known-percent-oman
mv panama ../known-percent-panama
mv peru ../known-percent-peru
mv philippines ../known-percent-philippines
mv poland ../known-percent-poland
mv portugal ../known-percent-portugal
mv qatar ../known-percent-qatar
mv reino-unido ../known-percent-reino-unido
mv republic-of-the-congo ../known-percent-republic-of-the-congo
mv republika-srpska ../known-percent-republika-srpska
mv reunion ../known-percent-reunion
mv romania ../known-percent-romania
mv russia ../known-percent-russia
mv république-tchèque ../known-percent-république-tchèque
mv sardinia ../known-percent-sardinia
mv saudi-arabia ../known-percent-saudi-arabia
mv scotland ../known-percent-scotland
mv senegal ../known-percent-senegal
mv serbia ../known-percent-serbia
mv singapore ../known-percent-singapore
mv slovakia ../known-percent-slovakia
mv slovenia ../known-percent-slovenia
mv south-africa ../known-percent-south-africa
mv south-east-asia ../known-percent-south-east-asia
mv south-korea ../known-percent-south-korea
mv spain ../known-percent-spain
mv sweden ../known-percent-sweden
mv switzerland ../known-percent-switzerland
mv thailand ../known-percent-thailand
mv trinidad-and-tobago ../known-percent-trinidad-and-tobago
mv tunisia ../known-percent-tunisia
mv turkey ../known-percent-turkey
mv ukraine ../known-percent-ukraine
mv united-arab-emirates ../known-percent-united-arab-emirates
mv united-kingdom ../known-percent-united-kingdom
mv united-states ../known-percent-united-states
mv vietnam ../known-percent-vietnam
mv world ../known-percent-world
mv yugoslavia ../known-percent-yugoslavia
mv česko ../known-percent-česko